### ISSUE TITLE
undefined reference to `__ink_generate_metadata' again

### ISSUE THREAD

**Issue by forgetso** [paritytech/cargo-contract#1254]
[This](https://github.com/paritytech/cargo-contract/issues/909) bug has reappeared due to a change to the template cargo.toml

Offending commit:
https://github.com/paritytech/cargo-contract/commit/94d96c5df60dc43d01f7329dbcef99c9454e9314

`std` needs to be enabled here:

https://github.com/paritytech/cargo-contract/blob/94d96c5df60dc43d01f7329dbcef99c9454e9314/crates/build/templates/generate-metadata/_Cargo.toml#L13

**Comment by SkymanOne** [comment]
I assume you are using `master` branch to compile the contract. Can you specify what version of ink! are you using in the contract? I could not reproduce the error compiling https://github.com/paritytech/ink-examples/tree/main/flipper with `cargo-contract` from master branch

**Comment by forgetso** [comment]
The problem for us is we cannot use the latest [parity contracts-ci-linux](https://hub.docker.com/r/paritytech/contracts-ci-linux/) as it fails with the metadata bug listed in this issue.

**Comment by forgetso** [comment]
We ended up building our own 3.0.1 version of contracts-ci-linux to get around this so that our CI runs.

https://hub.docker.com/layers/prosopo/contracts-ci-linux/3.0.1/images/sha256-127610c538d1fc74ead81e90fa557e72622e6a90fca57990d017e38792764585?context=repo
