### ISSUE TITLE
use of undeclared crate or module `scale_info`

### ISSUE THREAD

**Issue by GalaIO** [paritytech/cargo-contract#158]
when I run cargo +nightly contract build in 0.8.0, I got below
```rust
error[E0433]: failed to resolve: use of undeclared crate or module `scale_info`
  --> /Users/galaio/RustProjects/kylin-node/contracts/get_prices/lib.rs:36:66
   |
36 | Debug, Copy, Clone, PartialEq, Eq, scale::Encode, scale::Decode, scale_info::TypeInfo,
   |                                                                  ^^^^^^^^^^ use of undeclared crate or module `scale_info`
```
I have declare in cargo.toml, some thing wrong?
the project in [get_prices](https://github.com/Kylin-Network/kylin-contracts/tree/main/get_prices)
```toml

[dependencies]
ink_primitives = { git = "https://github.com/paritytech/ink", package = "ink_primitives", rev="1daf6a8e02a833067ee3eec905464a13a81b1cab", default-features = false }
ink_metadata = { git = "https://github.com/paritytech/ink", package = "ink_metadata", rev="1daf6a8e02a833067ee3eec905464a13a81b1cab", default-features = false, features = ["derive"], optional = true }
ink_env = { git = "https://github.com/paritytech/ink", package = "ink_env", rev="1daf6a8e02a833067ee3eec905464a13a81b1cab", default-features = false }
ink_storage = { git = "https://github.com/paritytech/ink", package = "ink_storage", rev="1daf6a8e02a833067ee3eec905464a13a81b1cab", default-features = false }
ink_lang = { git = "https://github.com/paritytech/ink", package = "ink_lang", rev="1daf6a8e02a833067ee3eec905464a13a81b1cab", default-features = false }
ink_prelude = { git = "https://github.com/paritytech/ink", package = "ink_prelude", rev="1daf6a8e02a833067ee3eec905464a13a81b1cab", default-features = false }


scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
scale-info = { version = "0.4", default-features = false, features = ["derive"], optional = true }

[lib]
name = "get_prices"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
]
ink-as-dependency = []
```

**Comment by ascjones** [comment]
`scale_info` is only required for generating the metadata in the `std` environment, so should be:

`#[cfg_attr(feature = "std", derive(scale_info::TypeInfo))]`
